package wsparser

// Code generated by /home/dimus/.cache/go-build/81/8158758236bd64395ecb7fa9535241c7aaac2024ee301c7fb56772b2ba7a1fe9-d/peg name.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleString
	ruleMarker
	ruleNamePart
	ruleItalicInfraspeciesWithAuthors
	ruleItalicInfraspecies
	ruleInfraRank
	ruleItalicName
	ruleBoldItalicName
	ruleSimpleItalicName
	ruleItalicContent
	ruleBareName
	ruleBareNameContent
	ruleUninomial
	ruleSpecies
	ruleSubspecies
	ruleNameUpperChar
	ruleUpperCharExtended
	ruleUpperChar
	ruleNameLowerChar
	ruleMiscodedChar
	ruleLowerCharExtended
	ruleLowerChar
	ruleUpperASCII
	ruleLowerASCII
	ruleParenthesizedAuthorPart
	ruleAuthorPart
	ruleAuthors
	ruleAuthor
	ruleItalicAuthorText
	ruleAuthorSep
	ruleAuthorTemplate
	ruleTemplateType
	ruleBracketAuthor
	ruleYear
	ruleParenthesizedYear
	ruleReference
	ruleTail
	rule_
	ruleEND
)

var rul3s = [...]string{
	"Unknown",
	"String",
	"Marker",
	"NamePart",
	"ItalicInfraspeciesWithAuthors",
	"ItalicInfraspecies",
	"InfraRank",
	"ItalicName",
	"BoldItalicName",
	"SimpleItalicName",
	"ItalicContent",
	"BareName",
	"BareNameContent",
	"Uninomial",
	"Species",
	"Subspecies",
	"NameUpperChar",
	"UpperCharExtended",
	"UpperChar",
	"NameLowerChar",
	"MiscodedChar",
	"LowerCharExtended",
	"LowerChar",
	"UpperASCII",
	"LowerASCII",
	"ParenthesizedAuthorPart",
	"AuthorPart",
	"Authors",
	"Author",
	"ItalicAuthorText",
	"AuthorSep",
	"AuthorTemplate",
	"TemplateType",
	"BracketAuthor",
	"Year",
	"ParenthesizedYear",
	"Reference",
	"Tail",
	"_",
	"END",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Parser struct {
	Buffer string
	buffer []rune
	rules  [40]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*Parser) error {
	return func(p *Parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Parser) error {
	return func(p *Parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Parser) Init(options ...func(*Parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 String <- <(_? Marker? _? NamePart ((ParenthesizedAuthorPart AuthorPart? ParenthesizedYear?) / (AuthorPart? (ParenthesizedYear / Year)?)) (Reference / Tail)? END)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position2, tokenIndex2 := position, tokenIndex
					if !_rules[rule_]() {
						goto l2
					}
					goto l3
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
			l3:
				{
					position4, tokenIndex4 := position, tokenIndex
					if !_rules[ruleMarker]() {
						goto l4
					}
					goto l5
				l4:
					position, tokenIndex = position4, tokenIndex4
				}
			l5:
				{
					position6, tokenIndex6 := position, tokenIndex
					if !_rules[rule_]() {
						goto l6
					}
					goto l7
				l6:
					position, tokenIndex = position6, tokenIndex6
				}
			l7:
				if !_rules[ruleNamePart]() {
					goto l0
				}
				{
					position8, tokenIndex8 := position, tokenIndex
					if !_rules[ruleParenthesizedAuthorPart]() {
						goto l9
					}
					{
						position10, tokenIndex10 := position, tokenIndex
						if !_rules[ruleAuthorPart]() {
							goto l10
						}
						goto l11
					l10:
						position, tokenIndex = position10, tokenIndex10
					}
				l11:
					{
						position12, tokenIndex12 := position, tokenIndex
						if !_rules[ruleParenthesizedYear]() {
							goto l12
						}
						goto l13
					l12:
						position, tokenIndex = position12, tokenIndex12
					}
				l13:
					goto l8
				l9:
					position, tokenIndex = position8, tokenIndex8
					{
						position14, tokenIndex14 := position, tokenIndex
						if !_rules[ruleAuthorPart]() {
							goto l14
						}
						goto l15
					l14:
						position, tokenIndex = position14, tokenIndex14
					}
				l15:
					{
						position16, tokenIndex16 := position, tokenIndex
						{
							position18, tokenIndex18 := position, tokenIndex
							if !_rules[ruleParenthesizedYear]() {
								goto l19
							}
							goto l18
						l19:
							position, tokenIndex = position18, tokenIndex18
							if !_rules[ruleYear]() {
								goto l16
							}
						}
					l18:
						goto l17
					l16:
						position, tokenIndex = position16, tokenIndex16
					}
				l17:
				}
			l8:
				{
					position20, tokenIndex20 := position, tokenIndex
					{
						position22, tokenIndex22 := position, tokenIndex
						if !_rules[ruleReference]() {
							goto l23
						}
						goto l22
					l23:
						position, tokenIndex = position22, tokenIndex22
						if !_rules[ruleTail]() {
							goto l20
						}
					}
				l22:
					goto l21
				l20:
					position, tokenIndex = position20, tokenIndex20
				}
			l21:
				if !_rules[ruleEND]() {
					goto l0
				}
				add(ruleString, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Marker <- <('×' / '†')> */
		func() bool {
			position24, tokenIndex24 := position, tokenIndex
			{
				position25 := position
				{
					position26, tokenIndex26 := position, tokenIndex
					if buffer[position] != rune('×') {
						goto l27
					}
					position++
					goto l26
				l27:
					position, tokenIndex = position26, tokenIndex26
					if buffer[position] != rune('†') {
						goto l24
					}
					position++
				}
			l26:
				add(ruleMarker, position25)
			}
			return true
		l24:
			position, tokenIndex = position24, tokenIndex24
			return false
		},
		/* 2 NamePart <- <(ItalicInfraspeciesWithAuthors / ItalicInfraspecies / ItalicName / BareName)> */
		func() bool {
			position28, tokenIndex28 := position, tokenIndex
			{
				position29 := position
				{
					position30, tokenIndex30 := position, tokenIndex
					if !_rules[ruleItalicInfraspeciesWithAuthors]() {
						goto l31
					}
					goto l30
				l31:
					position, tokenIndex = position30, tokenIndex30
					if !_rules[ruleItalicInfraspecies]() {
						goto l32
					}
					goto l30
				l32:
					position, tokenIndex = position30, tokenIndex30
					if !_rules[ruleItalicName]() {
						goto l33
					}
					goto l30
				l33:
					position, tokenIndex = position30, tokenIndex30
					if !_rules[ruleBareName]() {
						goto l28
					}
				}
			l30:
				add(ruleNamePart, position29)
			}
			return true
		l28:
			position, tokenIndex = position28, tokenIndex28
			return false
		},
		/* 3 ItalicInfraspeciesWithAuthors <- <('\'' '\'' ItalicContent ('\'' '\'') _ Authors _ InfraRank _ ('\'' '\'') ItalicContent ('\'' '\''))> */
		func() bool {
			position34, tokenIndex34 := position, tokenIndex
			{
				position35 := position
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				if !_rules[ruleItalicContent]() {
					goto l34
				}
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				if !_rules[rule_]() {
					goto l34
				}
				if !_rules[ruleAuthors]() {
					goto l34
				}
				if !_rules[rule_]() {
					goto l34
				}
				if !_rules[ruleInfraRank]() {
					goto l34
				}
				if !_rules[rule_]() {
					goto l34
				}
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				if !_rules[ruleItalicContent]() {
					goto l34
				}
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				if buffer[position] != rune('\'') {
					goto l34
				}
				position++
				add(ruleItalicInfraspeciesWithAuthors, position35)
			}
			return true
		l34:
			position, tokenIndex = position34, tokenIndex34
			return false
		},
		/* 4 ItalicInfraspecies <- <('\'' '\'' ItalicContent ('\'' '\'') _ InfraRank _ ('\'' '\'') ItalicContent ('\'' '\''))> */
		func() bool {
			position36, tokenIndex36 := position, tokenIndex
			{
				position37 := position
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				if !_rules[ruleItalicContent]() {
					goto l36
				}
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				if !_rules[rule_]() {
					goto l36
				}
				if !_rules[ruleInfraRank]() {
					goto l36
				}
				if !_rules[rule_]() {
					goto l36
				}
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				if !_rules[ruleItalicContent]() {
					goto l36
				}
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				if buffer[position] != rune('\'') {
					goto l36
				}
				position++
				add(ruleItalicInfraspecies, position37)
			}
			return true
		l36:
			position, tokenIndex = position36, tokenIndex36
			return false
		},
		/* 5 InfraRank <- <([a-z]+ '.'?)> */
		func() bool {
			position38, tokenIndex38 := position, tokenIndex
			{
				position39 := position
				if c := buffer[position]; c < rune('a') || c > rune('z') {
					goto l38
				}
				position++
			l40:
				{
					position41, tokenIndex41 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l41
					}
					position++
					goto l40
				l41:
					position, tokenIndex = position41, tokenIndex41
				}
				{
					position42, tokenIndex42 := position, tokenIndex
					if buffer[position] != rune('.') {
						goto l42
					}
					position++
					goto l43
				l42:
					position, tokenIndex = position42, tokenIndex42
				}
			l43:
				add(ruleInfraRank, position39)
			}
			return true
		l38:
			position, tokenIndex = position38, tokenIndex38
			return false
		},
		/* 6 ItalicName <- <(BoldItalicName / SimpleItalicName)> */
		func() bool {
			position44, tokenIndex44 := position, tokenIndex
			{
				position45 := position
				{
					position46, tokenIndex46 := position, tokenIndex
					if !_rules[ruleBoldItalicName]() {
						goto l47
					}
					goto l46
				l47:
					position, tokenIndex = position46, tokenIndex46
					if !_rules[ruleSimpleItalicName]() {
						goto l44
					}
				}
			l46:
				add(ruleItalicName, position45)
			}
			return true
		l44:
			position, tokenIndex = position44, tokenIndex44
			return false
		},
		/* 7 BoldItalicName <- <('\'' '\'' '\'' (!'\'' .)+ ('\'' '\'' '\''))> */
		func() bool {
			position48, tokenIndex48 := position, tokenIndex
			{
				position49 := position
				if buffer[position] != rune('\'') {
					goto l48
				}
				position++
				if buffer[position] != rune('\'') {
					goto l48
				}
				position++
				if buffer[position] != rune('\'') {
					goto l48
				}
				position++
				{
					position52, tokenIndex52 := position, tokenIndex
					if buffer[position] != rune('\'') {
						goto l52
					}
					position++
					goto l48
				l52:
					position, tokenIndex = position52, tokenIndex52
				}
				if !matchDot() {
					goto l48
				}
			l50:
				{
					position51, tokenIndex51 := position, tokenIndex
					{
						position53, tokenIndex53 := position, tokenIndex
						if buffer[position] != rune('\'') {
							goto l53
						}
						position++
						goto l51
					l53:
						position, tokenIndex = position53, tokenIndex53
					}
					if !matchDot() {
						goto l51
					}
					goto l50
				l51:
					position, tokenIndex = position51, tokenIndex51
				}
				if buffer[position] != rune('\'') {
					goto l48
				}
				position++
				if buffer[position] != rune('\'') {
					goto l48
				}
				position++
				if buffer[position] != rune('\'') {
					goto l48
				}
				position++
				add(ruleBoldItalicName, position49)
			}
			return true
		l48:
			position, tokenIndex = position48, tokenIndex48
			return false
		},
		/* 8 SimpleItalicName <- <('\'' '\'' ItalicContent ('\'' '\''))> */
		func() bool {
			position54, tokenIndex54 := position, tokenIndex
			{
				position55 := position
				if buffer[position] != rune('\'') {
					goto l54
				}
				position++
				if buffer[position] != rune('\'') {
					goto l54
				}
				position++
				if !_rules[ruleItalicContent]() {
					goto l54
				}
				if buffer[position] != rune('\'') {
					goto l54
				}
				position++
				if buffer[position] != rune('\'') {
					goto l54
				}
				position++
				add(ruleSimpleItalicName, position55)
			}
			return true
		l54:
			position, tokenIndex = position54, tokenIndex54
			return false
		},
		/* 9 ItalicContent <- <(!(('\'' '\'') / ('{' '{')) .)*> */
		func() bool {
			{
				position57 := position
			l58:
				{
					position59, tokenIndex59 := position, tokenIndex
					{
						position60, tokenIndex60 := position, tokenIndex
						{
							position61, tokenIndex61 := position, tokenIndex
							if buffer[position] != rune('\'') {
								goto l62
							}
							position++
							if buffer[position] != rune('\'') {
								goto l62
							}
							position++
							goto l61
						l62:
							position, tokenIndex = position61, tokenIndex61
							if buffer[position] != rune('{') {
								goto l60
							}
							position++
							if buffer[position] != rune('{') {
								goto l60
							}
							position++
						}
					l61:
						goto l59
					l60:
						position, tokenIndex = position60, tokenIndex60
					}
					if !matchDot() {
						goto l59
					}
					goto l58
				l59:
					position, tokenIndex = position59, tokenIndex59
				}
				add(ruleItalicContent, position57)
			}
			return true
		},
		/* 10 BareName <- <BareNameContent> */
		func() bool {
			position63, tokenIndex63 := position, tokenIndex
			{
				position64 := position
				if !_rules[ruleBareNameContent]() {
					goto l63
				}
				add(ruleBareName, position64)
			}
			return true
		l63:
			position, tokenIndex = position63, tokenIndex63
			return false
		},
		/* 11 BareNameContent <- <(Uninomial (_ Species (_ Subspecies)?)? &(ParenthesizedAuthorPart / AuthorPart / !.))> */
		func() bool {
			position65, tokenIndex65 := position, tokenIndex
			{
				position66 := position
				if !_rules[ruleUninomial]() {
					goto l65
				}
				{
					position67, tokenIndex67 := position, tokenIndex
					if !_rules[rule_]() {
						goto l67
					}
					if !_rules[ruleSpecies]() {
						goto l67
					}
					{
						position69, tokenIndex69 := position, tokenIndex
						if !_rules[rule_]() {
							goto l69
						}
						if !_rules[ruleSubspecies]() {
							goto l69
						}
						goto l70
					l69:
						position, tokenIndex = position69, tokenIndex69
					}
				l70:
					goto l68
				l67:
					position, tokenIndex = position67, tokenIndex67
				}
			l68:
				{
					position71, tokenIndex71 := position, tokenIndex
					{
						position72, tokenIndex72 := position, tokenIndex
						if !_rules[ruleParenthesizedAuthorPart]() {
							goto l73
						}
						goto l72
					l73:
						position, tokenIndex = position72, tokenIndex72
						if !_rules[ruleAuthorPart]() {
							goto l74
						}
						goto l72
					l74:
						position, tokenIndex = position72, tokenIndex72
						{
							position75, tokenIndex75 := position, tokenIndex
							if !matchDot() {
								goto l75
							}
							goto l65
						l75:
							position, tokenIndex = position75, tokenIndex75
						}
					}
				l72:
					position, tokenIndex = position71, tokenIndex71
				}
				add(ruleBareNameContent, position66)
			}
			return true
		l65:
			position, tokenIndex = position65, tokenIndex65
			return false
		},
		/* 12 Uninomial <- <(NameUpperChar NameLowerChar+)> */
		func() bool {
			position76, tokenIndex76 := position, tokenIndex
			{
				position77 := position
				if !_rules[ruleNameUpperChar]() {
					goto l76
				}
				if !_rules[ruleNameLowerChar]() {
					goto l76
				}
			l78:
				{
					position79, tokenIndex79 := position, tokenIndex
					if !_rules[ruleNameLowerChar]() {
						goto l79
					}
					goto l78
				l79:
					position, tokenIndex = position79, tokenIndex79
				}
				add(ruleUninomial, position77)
			}
			return true
		l76:
			position, tokenIndex = position76, tokenIndex76
			return false
		},
		/* 13 Species <- <NameLowerChar+> */
		func() bool {
			position80, tokenIndex80 := position, tokenIndex
			{
				position81 := position
				if !_rules[ruleNameLowerChar]() {
					goto l80
				}
			l82:
				{
					position83, tokenIndex83 := position, tokenIndex
					if !_rules[ruleNameLowerChar]() {
						goto l83
					}
					goto l82
				l83:
					position, tokenIndex = position83, tokenIndex83
				}
				add(ruleSpecies, position81)
			}
			return true
		l80:
			position, tokenIndex = position80, tokenIndex80
			return false
		},
		/* 14 Subspecies <- <NameLowerChar+> */
		func() bool {
			position84, tokenIndex84 := position, tokenIndex
			{
				position85 := position
				if !_rules[ruleNameLowerChar]() {
					goto l84
				}
			l86:
				{
					position87, tokenIndex87 := position, tokenIndex
					if !_rules[ruleNameLowerChar]() {
						goto l87
					}
					goto l86
				l87:
					position, tokenIndex = position87, tokenIndex87
				}
				add(ruleSubspecies, position85)
			}
			return true
		l84:
			position, tokenIndex = position84, tokenIndex84
			return false
		},
		/* 15 NameUpperChar <- <(UpperChar / UpperCharExtended)> */
		func() bool {
			position88, tokenIndex88 := position, tokenIndex
			{
				position89 := position
				{
					position90, tokenIndex90 := position, tokenIndex
					if !_rules[ruleUpperChar]() {
						goto l91
					}
					goto l90
				l91:
					position, tokenIndex = position90, tokenIndex90
					if !_rules[ruleUpperCharExtended]() {
						goto l88
					}
				}
			l90:
				add(ruleNameUpperChar, position89)
			}
			return true
		l88:
			position, tokenIndex = position88, tokenIndex88
			return false
		},
		/* 16 UpperCharExtended <- <('Æ' / 'Œ' / 'Ö')> */
		func() bool {
			position92, tokenIndex92 := position, tokenIndex
			{
				position93 := position
				{
					position94, tokenIndex94 := position, tokenIndex
					if buffer[position] != rune('Æ') {
						goto l95
					}
					position++
					goto l94
				l95:
					position, tokenIndex = position94, tokenIndex94
					if buffer[position] != rune('Œ') {
						goto l96
					}
					position++
					goto l94
				l96:
					position, tokenIndex = position94, tokenIndex94
					if buffer[position] != rune('Ö') {
						goto l92
					}
					position++
				}
			l94:
				add(ruleUpperCharExtended, position93)
			}
			return true
		l92:
			position, tokenIndex = position92, tokenIndex92
			return false
		},
		/* 17 UpperChar <- <UpperASCII> */
		func() bool {
			position97, tokenIndex97 := position, tokenIndex
			{
				position98 := position
				if !_rules[ruleUpperASCII]() {
					goto l97
				}
				add(ruleUpperChar, position98)
			}
			return true
		l97:
			position, tokenIndex = position97, tokenIndex97
			return false
		},
		/* 18 NameLowerChar <- <(LowerChar / LowerCharExtended / MiscodedChar)> */
		func() bool {
			position99, tokenIndex99 := position, tokenIndex
			{
				position100 := position
				{
					position101, tokenIndex101 := position, tokenIndex
					if !_rules[ruleLowerChar]() {
						goto l102
					}
					goto l101
				l102:
					position, tokenIndex = position101, tokenIndex101
					if !_rules[ruleLowerCharExtended]() {
						goto l103
					}
					goto l101
				l103:
					position, tokenIndex = position101, tokenIndex101
					if !_rules[ruleMiscodedChar]() {
						goto l99
					}
				}
			l101:
				add(ruleNameLowerChar, position100)
			}
			return true
		l99:
			position, tokenIndex = position99, tokenIndex99
			return false
		},
		/* 19 MiscodedChar <- <'�'> */
		func() bool {
			position104, tokenIndex104 := position, tokenIndex
			{
				position105 := position
				if buffer[position] != rune('�') {
					goto l104
				}
				position++
				add(ruleMiscodedChar, position105)
			}
			return true
		l104:
			position, tokenIndex = position104, tokenIndex104
			return false
		},
		/* 20 LowerCharExtended <- <('æ' / 'œ' / 'à' / 'â' / 'å' / 'ã' / 'ä' / 'á' / 'ç' / 'č' / 'é' / 'è' / 'ë' / 'í' / 'ì' / 'ï' / 'ň' / 'ñ' / 'ñ' / 'ó' / 'ò' / 'ô' / 'ø' / 'õ' / 'ö' / 'ú' / 'û' / 'ù' / 'ü' / 'ŕ' / 'ř' / 'ŗ' / 'ſ' / 'š' / 'š' / 'ş' / 'ß' / 'ž')> */
		func() bool {
			position106, tokenIndex106 := position, tokenIndex
			{
				position107 := position
				{
					position108, tokenIndex108 := position, tokenIndex
					if buffer[position] != rune('æ') {
						goto l109
					}
					position++
					goto l108
				l109:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('œ') {
						goto l110
					}
					position++
					goto l108
				l110:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('à') {
						goto l111
					}
					position++
					goto l108
				l111:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('â') {
						goto l112
					}
					position++
					goto l108
				l112:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('å') {
						goto l113
					}
					position++
					goto l108
				l113:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ã') {
						goto l114
					}
					position++
					goto l108
				l114:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ä') {
						goto l115
					}
					position++
					goto l108
				l115:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('á') {
						goto l116
					}
					position++
					goto l108
				l116:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ç') {
						goto l117
					}
					position++
					goto l108
				l117:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('č') {
						goto l118
					}
					position++
					goto l108
				l118:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('é') {
						goto l119
					}
					position++
					goto l108
				l119:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('è') {
						goto l120
					}
					position++
					goto l108
				l120:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ë') {
						goto l121
					}
					position++
					goto l108
				l121:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('í') {
						goto l122
					}
					position++
					goto l108
				l122:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ì') {
						goto l123
					}
					position++
					goto l108
				l123:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ï') {
						goto l124
					}
					position++
					goto l108
				l124:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ň') {
						goto l125
					}
					position++
					goto l108
				l125:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ñ') {
						goto l126
					}
					position++
					goto l108
				l126:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ñ') {
						goto l127
					}
					position++
					goto l108
				l127:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ó') {
						goto l128
					}
					position++
					goto l108
				l128:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ò') {
						goto l129
					}
					position++
					goto l108
				l129:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ô') {
						goto l130
					}
					position++
					goto l108
				l130:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ø') {
						goto l131
					}
					position++
					goto l108
				l131:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('õ') {
						goto l132
					}
					position++
					goto l108
				l132:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ö') {
						goto l133
					}
					position++
					goto l108
				l133:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ú') {
						goto l134
					}
					position++
					goto l108
				l134:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('û') {
						goto l135
					}
					position++
					goto l108
				l135:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ù') {
						goto l136
					}
					position++
					goto l108
				l136:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ü') {
						goto l137
					}
					position++
					goto l108
				l137:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ŕ') {
						goto l138
					}
					position++
					goto l108
				l138:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ř') {
						goto l139
					}
					position++
					goto l108
				l139:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ŗ') {
						goto l140
					}
					position++
					goto l108
				l140:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ſ') {
						goto l141
					}
					position++
					goto l108
				l141:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('š') {
						goto l142
					}
					position++
					goto l108
				l142:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('š') {
						goto l143
					}
					position++
					goto l108
				l143:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ş') {
						goto l144
					}
					position++
					goto l108
				l144:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ß') {
						goto l145
					}
					position++
					goto l108
				l145:
					position, tokenIndex = position108, tokenIndex108
					if buffer[position] != rune('ž') {
						goto l106
					}
					position++
				}
			l108:
				add(ruleLowerCharExtended, position107)
			}
			return true
		l106:
			position, tokenIndex = position106, tokenIndex106
			return false
		},
		/* 21 LowerChar <- <LowerASCII> */
		func() bool {
			position146, tokenIndex146 := position, tokenIndex
			{
				position147 := position
				if !_rules[ruleLowerASCII]() {
					goto l146
				}
				add(ruleLowerChar, position147)
			}
			return true
		l146:
			position, tokenIndex = position146, tokenIndex146
			return false
		},
		/* 22 UpperASCII <- <[A-Z]> */
		func() bool {
			position148, tokenIndex148 := position, tokenIndex
			{
				position149 := position
				if c := buffer[position]; c < rune('A') || c > rune('Z') {
					goto l148
				}
				position++
				add(ruleUpperASCII, position149)
			}
			return true
		l148:
			position, tokenIndex = position148, tokenIndex148
			return false
		},
		/* 23 LowerASCII <- <[a-z]> */
		func() bool {
			position150, tokenIndex150 := position, tokenIndex
			{
				position151 := position
				if c := buffer[position]; c < rune('a') || c > rune('z') {
					goto l150
				}
				position++
				add(ruleLowerASCII, position151)
			}
			return true
		l150:
			position, tokenIndex = position150, tokenIndex150
			return false
		},
		/* 24 ParenthesizedAuthorPart <- <(_? '(' _? Authors _? (',' _?)? Year? _? ')')> */
		func() bool {
			position152, tokenIndex152 := position, tokenIndex
			{
				position153 := position
				{
					position154, tokenIndex154 := position, tokenIndex
					if !_rules[rule_]() {
						goto l154
					}
					goto l155
				l154:
					position, tokenIndex = position154, tokenIndex154
				}
			l155:
				if buffer[position] != rune('(') {
					goto l152
				}
				position++
				{
					position156, tokenIndex156 := position, tokenIndex
					if !_rules[rule_]() {
						goto l156
					}
					goto l157
				l156:
					position, tokenIndex = position156, tokenIndex156
				}
			l157:
				if !_rules[ruleAuthors]() {
					goto l152
				}
				{
					position158, tokenIndex158 := position, tokenIndex
					if !_rules[rule_]() {
						goto l158
					}
					goto l159
				l158:
					position, tokenIndex = position158, tokenIndex158
				}
			l159:
				{
					position160, tokenIndex160 := position, tokenIndex
					if buffer[position] != rune(',') {
						goto l160
					}
					position++
					{
						position162, tokenIndex162 := position, tokenIndex
						if !_rules[rule_]() {
							goto l162
						}
						goto l163
					l162:
						position, tokenIndex = position162, tokenIndex162
					}
				l163:
					goto l161
				l160:
					position, tokenIndex = position160, tokenIndex160
				}
			l161:
				{
					position164, tokenIndex164 := position, tokenIndex
					if !_rules[ruleYear]() {
						goto l164
					}
					goto l165
				l164:
					position, tokenIndex = position164, tokenIndex164
				}
			l165:
				{
					position166, tokenIndex166 := position, tokenIndex
					if !_rules[rule_]() {
						goto l166
					}
					goto l167
				l166:
					position, tokenIndex = position166, tokenIndex166
				}
			l167:
				if buffer[position] != rune(')') {
					goto l152
				}
				position++
				add(ruleParenthesizedAuthorPart, position153)
			}
			return true
		l152:
			position, tokenIndex = position152, tokenIndex152
			return false
		},
		/* 25 AuthorPart <- <(_? Authors)> */
		func() bool {
			position168, tokenIndex168 := position, tokenIndex
			{
				position169 := position
				{
					position170, tokenIndex170 := position, tokenIndex
					if !_rules[rule_]() {
						goto l170
					}
					goto l171
				l170:
					position, tokenIndex = position170, tokenIndex170
				}
			l171:
				if !_rules[ruleAuthors]() {
					goto l168
				}
				add(ruleAuthorPart, position169)
			}
			return true
		l168:
			position, tokenIndex = position168, tokenIndex168
			return false
		},
		/* 26 Authors <- <(Author (_ AuthorSep _ Author)* (_ ItalicAuthorText)?)> */
		func() bool {
			position172, tokenIndex172 := position, tokenIndex
			{
				position173 := position
				if !_rules[ruleAuthor]() {
					goto l172
				}
			l174:
				{
					position175, tokenIndex175 := position, tokenIndex
					if !_rules[rule_]() {
						goto l175
					}
					if !_rules[ruleAuthorSep]() {
						goto l175
					}
					if !_rules[rule_]() {
						goto l175
					}
					if !_rules[ruleAuthor]() {
						goto l175
					}
					goto l174
				l175:
					position, tokenIndex = position175, tokenIndex175
				}
				{
					position176, tokenIndex176 := position, tokenIndex
					if !_rules[rule_]() {
						goto l176
					}
					if !_rules[ruleItalicAuthorText]() {
						goto l176
					}
					goto l177
				l176:
					position, tokenIndex = position176, tokenIndex176
				}
			l177:
				add(ruleAuthors, position173)
			}
			return true
		l172:
			position, tokenIndex = position172, tokenIndex172
			return false
		},
		/* 27 Author <- <(AuthorTemplate / BracketAuthor / ItalicAuthorText)> */
		func() bool {
			position178, tokenIndex178 := position, tokenIndex
			{
				position179 := position
				{
					position180, tokenIndex180 := position, tokenIndex
					if !_rules[ruleAuthorTemplate]() {
						goto l181
					}
					goto l180
				l181:
					position, tokenIndex = position180, tokenIndex180
					if !_rules[ruleBracketAuthor]() {
						goto l182
					}
					goto l180
				l182:
					position, tokenIndex = position180, tokenIndex180
					if !_rules[ruleItalicAuthorText]() {
						goto l178
					}
				}
			l180:
				add(ruleAuthor, position179)
			}
			return true
		l178:
			position, tokenIndex = position178, tokenIndex178
			return false
		},
		/* 28 ItalicAuthorText <- <('\'' '\'' (!('\'' '\'') .)+ ('\'' '\'') '.'?)> */
		func() bool {
			position183, tokenIndex183 := position, tokenIndex
			{
				position184 := position
				if buffer[position] != rune('\'') {
					goto l183
				}
				position++
				if buffer[position] != rune('\'') {
					goto l183
				}
				position++
				{
					position187, tokenIndex187 := position, tokenIndex
					if buffer[position] != rune('\'') {
						goto l187
					}
					position++
					if buffer[position] != rune('\'') {
						goto l187
					}
					position++
					goto l183
				l187:
					position, tokenIndex = position187, tokenIndex187
				}
				if !matchDot() {
					goto l183
				}
			l185:
				{
					position186, tokenIndex186 := position, tokenIndex
					{
						position188, tokenIndex188 := position, tokenIndex
						if buffer[position] != rune('\'') {
							goto l188
						}
						position++
						if buffer[position] != rune('\'') {
							goto l188
						}
						position++
						goto l186
					l188:
						position, tokenIndex = position188, tokenIndex188
					}
					if !matchDot() {
						goto l186
					}
					goto l185
				l186:
					position, tokenIndex = position186, tokenIndex186
				}
				if buffer[position] != rune('\'') {
					goto l183
				}
				position++
				if buffer[position] != rune('\'') {
					goto l183
				}
				position++
				{
					position189, tokenIndex189 := position, tokenIndex
					if buffer[position] != rune('.') {
						goto l189
					}
					position++
					goto l190
				l189:
					position, tokenIndex = position189, tokenIndex189
				}
			l190:
				add(ruleItalicAuthorText, position184)
			}
			return true
		l183:
			position, tokenIndex = position183, tokenIndex183
			return false
		},
		/* 29 AuthorSep <- <('&' / ('a' 'n' 'd') / ',')> */
		func() bool {
			position191, tokenIndex191 := position, tokenIndex
			{
				position192 := position
				{
					position193, tokenIndex193 := position, tokenIndex
					if buffer[position] != rune('&') {
						goto l194
					}
					position++
					goto l193
				l194:
					position, tokenIndex = position193, tokenIndex193
					if buffer[position] != rune('a') {
						goto l195
					}
					position++
					if buffer[position] != rune('n') {
						goto l195
					}
					position++
					if buffer[position] != rune('d') {
						goto l195
					}
					position++
					goto l193
				l195:
					position, tokenIndex = position193, tokenIndex193
					if buffer[position] != rune(',') {
						goto l191
					}
					position++
				}
			l193:
				add(ruleAuthorSep, position192)
			}
			return true
		l191:
			position, tokenIndex = position191, tokenIndex191
			return false
		},
		/* 30 AuthorTemplate <- <('{' '{' TemplateType '|' (!('}' '}') .)+ ('}' '}'))> */
		func() bool {
			position196, tokenIndex196 := position, tokenIndex
			{
				position197 := position
				if buffer[position] != rune('{') {
					goto l196
				}
				position++
				if buffer[position] != rune('{') {
					goto l196
				}
				position++
				if !_rules[ruleTemplateType]() {
					goto l196
				}
				if buffer[position] != rune('|') {
					goto l196
				}
				position++
				{
					position200, tokenIndex200 := position, tokenIndex
					if buffer[position] != rune('}') {
						goto l200
					}
					position++
					if buffer[position] != rune('}') {
						goto l200
					}
					position++
					goto l196
				l200:
					position, tokenIndex = position200, tokenIndex200
				}
				if !matchDot() {
					goto l196
				}
			l198:
				{
					position199, tokenIndex199 := position, tokenIndex
					{
						position201, tokenIndex201 := position, tokenIndex
						if buffer[position] != rune('}') {
							goto l201
						}
						position++
						if buffer[position] != rune('}') {
							goto l201
						}
						position++
						goto l199
					l201:
						position, tokenIndex = position201, tokenIndex201
					}
					if !matchDot() {
						goto l199
					}
					goto l198
				l199:
					position, tokenIndex = position199, tokenIndex199
				}
				if buffer[position] != rune('}') {
					goto l196
				}
				position++
				if buffer[position] != rune('}') {
					goto l196
				}
				position++
				add(ruleAuthorTemplate, position197)
			}
			return true
		l196:
			position, tokenIndex = position196, tokenIndex196
			return false
		},
		/* 31 TemplateType <- <((('a' / 'A') ('u' / 'U') ('t' / 'T')) / (('a' / 'A') ('u' / 'U')) / ('a' / 'A'))> */
		func() bool {
			position202, tokenIndex202 := position, tokenIndex
			{
				position203 := position
				{
					position204, tokenIndex204 := position, tokenIndex
					{
						position206, tokenIndex206 := position, tokenIndex
						if buffer[position] != rune('a') {
							goto l207
						}
						position++
						goto l206
					l207:
						position, tokenIndex = position206, tokenIndex206
						if buffer[position] != rune('A') {
							goto l205
						}
						position++
					}
				l206:
					{
						position208, tokenIndex208 := position, tokenIndex
						if buffer[position] != rune('u') {
							goto l209
						}
						position++
						goto l208
					l209:
						position, tokenIndex = position208, tokenIndex208
						if buffer[position] != rune('U') {
							goto l205
						}
						position++
					}
				l208:
					{
						position210, tokenIndex210 := position, tokenIndex
						if buffer[position] != rune('t') {
							goto l211
						}
						position++
						goto l210
					l211:
						position, tokenIndex = position210, tokenIndex210
						if buffer[position] != rune('T') {
							goto l205
						}
						position++
					}
				l210:
					goto l204
				l205:
					position, tokenIndex = position204, tokenIndex204
					{
						position213, tokenIndex213 := position, tokenIndex
						if buffer[position] != rune('a') {
							goto l214
						}
						position++
						goto l213
					l214:
						position, tokenIndex = position213, tokenIndex213
						if buffer[position] != rune('A') {
							goto l212
						}
						position++
					}
				l213:
					{
						position215, tokenIndex215 := position, tokenIndex
						if buffer[position] != rune('u') {
							goto l216
						}
						position++
						goto l215
					l216:
						position, tokenIndex = position215, tokenIndex215
						if buffer[position] != rune('U') {
							goto l212
						}
						position++
					}
				l215:
					goto l204
				l212:
					position, tokenIndex = position204, tokenIndex204
					{
						position217, tokenIndex217 := position, tokenIndex
						if buffer[position] != rune('a') {
							goto l218
						}
						position++
						goto l217
					l218:
						position, tokenIndex = position217, tokenIndex217
						if buffer[position] != rune('A') {
							goto l202
						}
						position++
					}
				l217:
				}
			l204:
				add(ruleTemplateType, position203)
			}
			return true
		l202:
			position, tokenIndex = position202, tokenIndex202
			return false
		},
		/* 32 BracketAuthor <- <('[' '[' (!(']' / '|') .)+ ('|' (!']' .)+)? (']' ']'))> */
		func() bool {
			position219, tokenIndex219 := position, tokenIndex
			{
				position220 := position
				if buffer[position] != rune('[') {
					goto l219
				}
				position++
				if buffer[position] != rune('[') {
					goto l219
				}
				position++
				{
					position223, tokenIndex223 := position, tokenIndex
					{
						position224, tokenIndex224 := position, tokenIndex
						if buffer[position] != rune(']') {
							goto l225
						}
						position++
						goto l224
					l225:
						position, tokenIndex = position224, tokenIndex224
						if buffer[position] != rune('|') {
							goto l223
						}
						position++
					}
				l224:
					goto l219
				l223:
					position, tokenIndex = position223, tokenIndex223
				}
				if !matchDot() {
					goto l219
				}
			l221:
				{
					position222, tokenIndex222 := position, tokenIndex
					{
						position226, tokenIndex226 := position, tokenIndex
						{
							position227, tokenIndex227 := position, tokenIndex
							if buffer[position] != rune(']') {
								goto l228
							}
							position++
							goto l227
						l228:
							position, tokenIndex = position227, tokenIndex227
							if buffer[position] != rune('|') {
								goto l226
							}
							position++
						}
					l227:
						goto l222
					l226:
						position, tokenIndex = position226, tokenIndex226
					}
					if !matchDot() {
						goto l222
					}
					goto l221
				l222:
					position, tokenIndex = position222, tokenIndex222
				}
				{
					position229, tokenIndex229 := position, tokenIndex
					if buffer[position] != rune('|') {
						goto l229
					}
					position++
					{
						position233, tokenIndex233 := position, tokenIndex
						if buffer[position] != rune(']') {
							goto l233
						}
						position++
						goto l229
					l233:
						position, tokenIndex = position233, tokenIndex233
					}
					if !matchDot() {
						goto l229
					}
				l231:
					{
						position232, tokenIndex232 := position, tokenIndex
						{
							position234, tokenIndex234 := position, tokenIndex
							if buffer[position] != rune(']') {
								goto l234
							}
							position++
							goto l232
						l234:
							position, tokenIndex = position234, tokenIndex234
						}
						if !matchDot() {
							goto l232
						}
						goto l231
					l232:
						position, tokenIndex = position232, tokenIndex232
					}
					goto l230
				l229:
					position, tokenIndex = position229, tokenIndex229
				}
			l230:
				if buffer[position] != rune(']') {
					goto l219
				}
				position++
				if buffer[position] != rune(']') {
					goto l219
				}
				position++
				add(ruleBracketAuthor, position220)
			}
			return true
		l219:
			position, tokenIndex = position219, tokenIndex219
			return false
		},
		/* 33 Year <- <(_? (',' _?)? [0-9] [0-9] [0-9] [0-9])> */
		func() bool {
			position235, tokenIndex235 := position, tokenIndex
			{
				position236 := position
				{
					position237, tokenIndex237 := position, tokenIndex
					if !_rules[rule_]() {
						goto l237
					}
					goto l238
				l237:
					position, tokenIndex = position237, tokenIndex237
				}
			l238:
				{
					position239, tokenIndex239 := position, tokenIndex
					if buffer[position] != rune(',') {
						goto l239
					}
					position++
					{
						position241, tokenIndex241 := position, tokenIndex
						if !_rules[rule_]() {
							goto l241
						}
						goto l242
					l241:
						position, tokenIndex = position241, tokenIndex241
					}
				l242:
					goto l240
				l239:
					position, tokenIndex = position239, tokenIndex239
				}
			l240:
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l235
				}
				position++
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l235
				}
				position++
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l235
				}
				position++
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l235
				}
				position++
				add(ruleYear, position236)
			}
			return true
		l235:
			position, tokenIndex = position235, tokenIndex235
			return false
		},
		/* 34 ParenthesizedYear <- <(_? '(' _? [0-9] [0-9] [0-9] [0-9] _? ')')> */
		func() bool {
			position243, tokenIndex243 := position, tokenIndex
			{
				position244 := position
				{
					position245, tokenIndex245 := position, tokenIndex
					if !_rules[rule_]() {
						goto l245
					}
					goto l246
				l245:
					position, tokenIndex = position245, tokenIndex245
				}
			l246:
				if buffer[position] != rune('(') {
					goto l243
				}
				position++
				{
					position247, tokenIndex247 := position, tokenIndex
					if !_rules[rule_]() {
						goto l247
					}
					goto l248
				l247:
					position, tokenIndex = position247, tokenIndex247
				}
			l248:
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l243
				}
				position++
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l243
				}
				position++
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l243
				}
				position++
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l243
				}
				position++
				{
					position249, tokenIndex249 := position, tokenIndex
					if !_rules[rule_]() {
						goto l249
					}
					goto l250
				l249:
					position, tokenIndex = position249, tokenIndex249
				}
			l250:
				if buffer[position] != rune(')') {
					goto l243
				}
				position++
				add(ruleParenthesizedYear, position244)
			}
			return true
		l243:
			position, tokenIndex = position243, tokenIndex243
			return false
		},
		/* 35 Reference <- <(_? ':' .*)> */
		func() bool {
			position251, tokenIndex251 := position, tokenIndex
			{
				position252 := position
				{
					position253, tokenIndex253 := position, tokenIndex
					if !_rules[rule_]() {
						goto l253
					}
					goto l254
				l253:
					position, tokenIndex = position253, tokenIndex253
				}
			l254:
				if buffer[position] != rune(':') {
					goto l251
				}
				position++
			l255:
				{
					position256, tokenIndex256 := position, tokenIndex
					if !matchDot() {
						goto l256
					}
					goto l255
				l256:
					position, tokenIndex = position256, tokenIndex256
				}
				add(ruleReference, position252)
			}
			return true
		l251:
			position, tokenIndex = position251, tokenIndex251
			return false
		},
		/* 36 Tail <- <(_? !('E' 'N' 'D') .+)> */
		func() bool {
			position257, tokenIndex257 := position, tokenIndex
			{
				position258 := position
				{
					position259, tokenIndex259 := position, tokenIndex
					if !_rules[rule_]() {
						goto l259
					}
					goto l260
				l259:
					position, tokenIndex = position259, tokenIndex259
				}
			l260:
				{
					position261, tokenIndex261 := position, tokenIndex
					if buffer[position] != rune('E') {
						goto l261
					}
					position++
					if buffer[position] != rune('N') {
						goto l261
					}
					position++
					if buffer[position] != rune('D') {
						goto l261
					}
					position++
					goto l257
				l261:
					position, tokenIndex = position261, tokenIndex261
				}
				if !matchDot() {
					goto l257
				}
			l262:
				{
					position263, tokenIndex263 := position, tokenIndex
					if !matchDot() {
						goto l263
					}
					goto l262
				l263:
					position, tokenIndex = position263, tokenIndex263
				}
				add(ruleTail, position258)
			}
			return true
		l257:
			position, tokenIndex = position257, tokenIndex257
			return false
		},
		/* 37 _ <- <(' ' / '\t' / '\r' / '\n')+> */
		func() bool {
			position264, tokenIndex264 := position, tokenIndex
			{
				position265 := position
				{
					position268, tokenIndex268 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l269
					}
					position++
					goto l268
				l269:
					position, tokenIndex = position268, tokenIndex268
					if buffer[position] != rune('\t') {
						goto l270
					}
					position++
					goto l268
				l270:
					position, tokenIndex = position268, tokenIndex268
					if buffer[position] != rune('\r') {
						goto l271
					}
					position++
					goto l268
				l271:
					position, tokenIndex = position268, tokenIndex268
					if buffer[position] != rune('\n') {
						goto l264
					}
					position++
				}
			l268:
			l266:
				{
					position267, tokenIndex267 := position, tokenIndex
					{
						position272, tokenIndex272 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l273
						}
						position++
						goto l272
					l273:
						position, tokenIndex = position272, tokenIndex272
						if buffer[position] != rune('\t') {
							goto l274
						}
						position++
						goto l272
					l274:
						position, tokenIndex = position272, tokenIndex272
						if buffer[position] != rune('\r') {
							goto l275
						}
						position++
						goto l272
					l275:
						position, tokenIndex = position272, tokenIndex272
						if buffer[position] != rune('\n') {
							goto l267
						}
						position++
					}
				l272:
					goto l266
				l267:
					position, tokenIndex = position267, tokenIndex267
				}
				add(rule_, position265)
			}
			return true
		l264:
			position, tokenIndex = position264, tokenIndex264
			return false
		},
		/* 38 END <- <!.> */
		func() bool {
			position276, tokenIndex276 := position, tokenIndex
			{
				position277 := position
				{
					position278, tokenIndex278 := position, tokenIndex
					if !matchDot() {
						goto l278
					}
					goto l276
				l278:
					position, tokenIndex = position278, tokenIndex278
				}
				add(ruleEND, position277)
			}
			return true
		l276:
			position, tokenIndex = position276, tokenIndex276
			return false
		},
	}
	p.rules = _rules
	return nil
}
