package paleodb

import "github.com/sfborg/sflib/pkg/coldp"

func (p *paleodb) importMeta() error {
	meta := coldp.Meta{
		Title: "The Paleobiology Database",
		Alias: "PBDB",
		Description: `The Paleobiology Database is a public database of paleontological data that anyone can use, 
maintained by an international non-governmental group of paleontologists.
  
Fossil occurrences from scientific publications are added to the database by our contributing members. 
Thanks to our membership, which includes nearly 400 scientists from over 130 institutions in 24 countries, 
the Paleobiology Database is able to provide scientists and the public with information about the fossil record.
`,
		Issued:  p.cfg.ArchiveDate,
		Version: p.cfg.ArchiveVersion,

		Contact: &coldp.Actor{
			Email:        "info@paleobiodb.org",
			Organization: "The Paleobiology Database",
		},
		Contributors: contributors,
		Creators:     creators,
		URL:          "https://paleobiodb.org",

		License:         "CC BY",
		GeographicScope: "global",
		Confidence:      5,
		Completeness:    100,
		Logo:            "https://paleobiodb.org/build/logos/pbdb_color.png",
		Notes:           "Generated by https://github.com/sfborg/harvester",
	}
	p.sfga.InsertMeta(&meta)

	return nil
}

var contributors = []coldp.Actor{
	{Family: "McClennen", Given: "Michael", Note: "Tech Team"},
	{Family: "Peters", Given: "Shanan", Note: "Tech Team"},
	{Family: "Behboudi", Given: "Noushin", Note: "Tech Team"},
	{Family: "Döring", Given: "Markus",
		Orcid:   "0000-0001-7757-1889",
		Country: "Germany",
		City:    "Berlin",
		Email:   "mdoering@gbif.org",
		Note:    "Developer of ColDP generator code"},
}

var creators = []coldp.Actor{
	{
		Given:  "Mark",
		Family: "Uhen",
		Note:   "Executive Committee (chair)",
	},
	{
		Given:  "Philip",
		Family: "Mannion",
		Note:   "Executive Committee (secretary)",
	},
	{
		Given:  "Bethany",
		Family: "Allen",
		Note:   "Executive Committee",
	},
	{
		Given:  "Matthew",
		Family: "Clapham",
		Note:   "Executive Committee",
	},
	{
		Given:  "Emma",
		Family: "Dunne",
		Note:   "Executive Committee",
	},
	{
		Given:  "Phillip",
		Family: "Jardine",
		Note:   "Executive Committee",
	},
	{
		Given:  "Ádám",
		Family: "Kocsis",
		Note:   "Executive Committee",
	},
	{
		Given:  "Andrew",
		Family: "Krug",
		Note:   "Executive Committee",
	},
	{
		Given:  "Noel",
		Family: "Heim",
		Note:   "Executive Committee",
	},
	{
		Given:  "Phil",
		Family: "Novack},{Gottshall",
		Note:   "Executive Committee",
	},
	{
		Given:  "Catalina",
		Family: "Pimiento",
		Note:   "Executive Committee",
	},
	{
		Given:  "Peter",
		Family: "Wagner",
		Note:   "Executive Committee",
	},
}
